Feat: function sdk getAdditionalProperty
ar-e-co/deco-components pull request #5
Opened 2024-05-10 16:45 UTC by DiegoOlive29

Criei uma função para pegar as informações que vão ir na tag, pois verifiquei que não são todas as imagens que tem as mesma, vai bastar cadastrar as tags no admim para funcionar na função corretamente.

Não usei o mesma função que pega informação adicionais do produto, pois elas são cadastradas com nome padrão que se repete para diversos outros campos.

2024-05-14 11:27 UTC, pedrobernardina requested changes

2024-05-14 11:27 UTC, pedrobernardina commented on components/product/ProductItemPDP.tsx
> +        {actionOnClick == "modal" &&
```suggestion
        {actionOnClick == "zoom" &&
```

2024-05-14 11:27 UTC, pedrobernardina commented on components/product/ProductItemPDP.tsx
> +        />
Acho que é melhor evitar isso daqui.. não tem uma forma melhor de fazermos a mesma coisa não, usando hooks?

2024-05-14 11:27 UTC, pedrobernardina commented on components/product/ProductItemPDP.tsx
> +export default function ProductItemPDP({alt,url,index,actionOnClick="zoom",onMouseOver=false,height,width}: Props) {
Se esse componente é o de imagem acho esse nome ruim.

`ProductImage` é melhor

2024-05-14 11:27 UTC, pedrobernardina commented on components/product/ProductItemPDP.tsx
> +        <Slider.Item
Vale rancar esse Slider.Item, porque não da para assumir que a imagem sempre estará dentro de um Slider.

2024-05-14 11:33 UTC, pedrobernardina commented
Esse MR parece que faz algo diferente do que o título sugere

2024-05-16 23:33 UTC, DiegoOlive29 commented on components/product/ProductItemPDP.tsx
> +        {actionOnClick == "modal" &&
Essa logica é pra abrir o modal não pra dar o zoom na imagem. 
O modal é quando clica igual na oficina.

O zoom da imagem é feito pelo :
```
<script
            dangerouslySetInnerHTML={{
            __html: `(${imgZoom.toString()})()`,
            }}
        />
```

2024-05-17 15:47 UTC, DiegoOlive29 commented on components/product/ProductItemPDP.tsx
> +        />
Removi a função e agora a funcionalidade esta atrelada ao onClick da imagem.

2024-05-17 19:21 UTC, DiegoOlive29 commented on components/product/ProductItemPDP.tsx
> +        <Slider.Item
Removi, porem tive que adicionar um novo div para o efeito de zoom se manter ainda.

2024-05-23 02:29 UTC, DiegoOlive29 commented
Foi feita correções no estilo de acordo com o site atual.

2024-05-29 18:10 UTC, merged